# Generated by Django 4.2 on 2023-05-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='complete_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='complete time'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='due_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='due time'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='start_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='start'),
        ),
    ]
