# Generated by Django 4.2 on 2023-05-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0002_alter_workorder_complete_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='complete_time',
            field=models.DateTimeField(null=True, verbose_name='complete time'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='due_time',
            field=models.DateTimeField(null=True, verbose_name='due time'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='Updated at'),
        ),
    ]
