# Generated by Django 4.2 on 2023-05-02 15:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work_center', '0001_initial'),
        ('workplace', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('father_name', models.CharField(max_length=255, verbose_name='Fathers name')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='email')),
                ('city', models.CharField(max_length=255, verbose_name='city')),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='Updated at')),
                ('job_title', models.CharField(max_length=255, verbose_name='job title')),
                ('rfid_uid', models.CharField(max_length=20, null=True, unique=True, verbose_name='Card ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('workcenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work_center.workcenter', verbose_name='work center')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workplace.workplace', verbose_name='workplace')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
