# Generated by Django 4.2 on 2023-05-02 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.CharField(max_length=255, null=True, verbose_name='job title'),
        ),
        migrations.AlterField(
            model_name='user',
            name='workplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workplace.workplace', verbose_name='workplace'),
        ),
    ]
